# Generated by Django 5.1.5 on 2025-02-04 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notes",
            name="likes",
            field=models.IntegerField(default=0),
        ),
    ]
