# Generated by Django 5.1.5 on 2025-02-05 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0004_notes_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="notes",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
    ]
